name: avas_transfer
description: BML Avas Transfer

publish_to: 'none'

version: 1.0.4+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  http: ^0.13.1
  intl: ^0.17.0
  sms: ^0.2.4
  permission_handler: ^6.1.1
  path_provider: ^2.0.1
  share_extend: ^1.1.9
#  flutter_barcode_scanner: ^1.0.2
  get_storage: ^2.0.1
#  flutter_mobile_vision: ^0.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/